### ISSUE TITLE
bazel-skylib not found

### ISSUE THREAD

**Issue by julovi** [google/eidos-audition#1]
Hi,

I'm trying to install eidos, but I'm receiving this warning:
`WARNING: Download from https://github.com/bazelbuild/bazel-skylib/archive/master.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
`
followed by an error.

Could you help me to solve this problem?

**Comment by imjasonh** [comment]
https://github.com/google/eidos-audition/blob/master/WORKSPACE.bazel needs to reference bazel-skylib's main branch, they renamed the master branch.

To avoid issues like this in the future this repo should reference dependencies by commit instead of movable branch names.

**Comment by julovi** [comment]
Thanks Jason,
I was able to install eidos-audition with your help. I have to say that besides changing the `urls` entry to `"https://github.com/bazelbuild/bazel-skylib/archive/main.zip"` I also needed to change the `strip_prefix` to `"bazel-skylib-main"`. In addition, the instructions don't mention that you need to have installed: 
`wget`, 
`sox`,
and `matplotlib`. The first two I install via brew; the last one via ` python3 -mpip install matplotlib`
I'm leaving this comment here in case someone in the future stumble upon the same problem.

Thanks again!
