### ISSUE TITLE
The function for resampling in fractional_gaussian_noise.cc

### ISSUE THREAD

**Issue by wjassim** [google/eidos-audition#5]
Hello

Thank you so much for sharing this wonderful instrument. 

I have a question regarding the fast (precise) fractional Gaussian noise and Brownian motion generator in C++ (`third_party/audition/models/bruce_carney/fractional_gaussian_noise.cc`). 

In the original MATLAB version (`ffGn.m`), the data is resampled to `1/tdres` :

```matlab
% Resampling back to original (1/tdres): match with the AN model
y = resample(y,resamp,1);  % Resampling to match with the AN model
```

However, there isn't a resampling function like that in your `fractional_gaussian_noise.cc` to carry out data resampling. Is there something that I'm missing here?

Thank you for your time.

Best regards,

**Comment by agutkin** [comment]
Hi,

This is used in the [`Bruce2018HairCellSynapse`](https://github.com/google/eidos-audition/blob/main/third_party/audition/models/bruce_carney/bruce2018_hair_cell_synapse_model.cc)  synapse model where the resampling and power law adjustments do occur later on (line 74 onwards). However, I am not 100% sure that this particular C++ implementation is bulletproof - it could very well be that I based it on an older hacked version. Unfortunately putting these things together involved some archeology and the implementation may have serious bugs in it.

**Comment by wjassim** [comment]
I get it. Thank you very much.

**Comment by wjassim** [comment]
That's great; I get it. I sincerely appreciate that.
